### ISSUE TITLE
Render cached HTML page instead of showing the HTML output

### ISSUE THREAD

**Issue by olivierobert** [jigarakatidus/google-keyword-insights#14]
In terms of UX/UI, showing the HTML code does not provide many benefits. Instead, user should be able to see the actual page:

![image](https://user-images.githubusercontent.com/696529/132176632-cad780f7-06c8-4ab7-9e42-fc1848d070e5.png)
 
There lies a bit of technical challenge to do so. That's the interesting bit :-)

**Comment by jigarakatidus** [comment]
I had thought of this. #18 (not merged yet)

My only concern was XSS attack. Although there is no User Input. I did not feel confident about exposing html this way.

Sample Output:
<img width="1213" alt="Screenshot 2021-09-06 at 11 54 07 PM" src="https://user-images.githubusercontent.com/3132291/132252476-f6345013-e25c-4e1b-ba4a-fa080d1a81e3.png">

Other way I can think of is htmltopdf or htmltojpeg.

**Comment by olivierobert** [comment]
What about using an iframe as it provides isolation from the parent page?

**Comment by jigarakatidus** [comment]
Good suggestion. Wasn't aware of `srcdoc` attribute.  Merged #18 

<img width="1395" alt="Screenshot 2021-09-07 at 10 01 01 AM" src="https://user-images.githubusercontent.com/3132291/132284619-18335ead-86b8-4515-b468-44c8579c883d.png">
