### ISSUE TITLE
Local setup fails 

### ISSUE THREAD

**Issue by olivierobert** [jigarakatidus/google-keyword-insights#8]
## Expected

The project can be set up on a local machine using the instructions in README.

## Actual

When using Mac OS (Big Sur), the setup with Docker fails:

![image](https://user-images.githubusercontent.com/696529/132155434-077529b2-1420-4873-9d8d-a54351b246e3.png)

## Step to reproduce

1. Open a terminal in the root of the project
2. Use the command:

```
docker run --rm -u "$(id -u):$(id -g)" -w /opt laravelsail/php80-composer:latest composer install --ignore-platform-reqs
```

The following Docker and Docker Compose versions are used:

![image](https://user-images.githubusercontent.com/696529/132155632-db4b559e-cf53-4f4f-9e55-ba15fb1c9faf.png)

**Comment by jigarakatidus** [comment]
Usually this happens when volume is not mounted or mounted incorrectly.

Further looking into this, noticed that `-v $(pwd):/opt ` is missing from your command.

**Comment by olivierobert** [comment]
I forgot to mention that I also previously ran into some issues with the command format:

So I tried to modify the command on my end but forgot to add back the volume bit.

When I fall back on the provide command, this is the issue I face:

![image](https://user-images.githubusercontent.com/696529/132168772-526dd6cb-9124-4924-950d-bfc4ca46b410.png)

**Comment by jigarakatidus** [comment]
`pwd` might be having space.

Try with `-v "$(pwd):/opt"`.

**Comment by olivierobert** [comment]
Indeed, the issue was with the volume name 👍
